### ISSUE TITLE
membuat halaman dosen

### ISSUE THREAD

**Issue by feriksetiawan18** [feriksetiawan18/proyek-web-nim-2020#1]
buatlah kode program menggunakan CI untuk menampilkan data dosen. push ke dalam branch dosen. adapun file yang harus di push antara lain adalah file model, view, dan controller

**Comment by faisaladi1990z** [comment]
Gua gapaham

Pada tanggal Min, 6 Des 2020 21:09, feriksetiawan18 <
notifications@github.com> menulis:

**Comment by feriksetiawan18** [comment]
ayo bisa sal

**Comment by faisaladi09** [comment]
tugas anda sudah selesai

**Comment by feriksetiawan18** [comment]
baik terimaksih

**Comment by faisaladi09** [comment]
Done.

Pada tanggal Sel, 8 Des 2020 pukul 22.09 feriksetiawan18 <
notifications@github.com> menulis:
